### ISSUE TITLE
Remove discord from midia kit

### ISSUE THREAD

**Issue by winchestercanal** [doras-to/doras#101]
### Tell us what you think!

I don't use Discord for contact, so I don't want it to appear on my Media Kit page!

**Comment by tommerty** [comment]
Hey! Ah, that shouldn't happen, it should remove the box if it's empty. We're working on a fix right now!

**Comment by tommerty** [comment]
@rafaelsouzams that should be fixed! Please let us know if there's anything else!

**Comment by winchestercanal** [comment]
The button still appears on my page even without any information on it
https://doras.to/winchestercanal/mediakit

**Comment by tommerty** [comment]
Sorry, it's not fully deployed right now, still building. Give Vercel a minute or two 😄

**Comment by tommerty** [comment]
Oops, it's botched the email! Sit tight @rafaelsouzams, we're working on this! Next ping will be when it's fully deployed and fixed 😄

**Comment by winchestercanal** [comment]
now is fixed hahaha, thank you!! 😄❤️

**Comment by winchestercanal** [comment]
But now the email is being displayed all the time, and it's bigger than the background box hahahah it works for me, but feel free to correct this at your time when you can, just for aesthetic reasons!!
![image](https://github.com/doras-to/doras/assets/25182245/d42d916c-6d34-44f9-8389-0d5c18e5be15)

Thanks again.

**Comment by tommerty** [comment]
Yeah, it's all fucky, doing all sorts. We're still cooking, might just need a wee bit more time mate <3

**Comment by tommerty** [comment]
Finally sorted! I simplified it to literally just hide it if null! Hope you enjoy! 😀
